# -*- coding: utf-8 -*-
"""kannan.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Kv_MMbkgK7_JC52jhQtYDJw-Uqramjg
"""

class example:
  def BMI():
          BMI=int(input("Enter the BMI Index:"))
          if(BMI<18.5):
            print("underweight")
            messsage="underweight"
          elif(BMI<25):
              print("Normalweight")
              message="Normalweight"
          elif(BMI<30):
              print("Overweight")
              message="Overweight"
          elif(BMI<35):
              print("very Overweight")
              message="very Overweight"
          return message